export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const SUB_QUANTITY = 'SUB_QUANTITY';
export const ADD_QUANTITY = 'ADD_QUANTITY';
export const DEPOSIT_COST = 'DEPOSIT_COST';
export const WITHDRAW_COST = 'WITHDRAW_COST';